apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway
  namespace: knativetutorial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: knativetutorial
