apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-operator
  labels:
    app: k8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: k8s-operator
    spec:
      containers:
      - name: k8s-operator
        image: salaboy/k8s-operator:operator2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      serviceAccountName: k8s-operator