apiVersion: v1
appVersion: 1.0.2
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: k8s-operator
version: 1.0.2
